/**
 * githubCredentialHelper.ts — the scripts and shell commands that deliver a
 * GitHub token to git and `gh` without ever putting it in an env var, git
 * config, argv, or the bind-mounted worktree.
 *
 * Layout under a runtime directory D (container: tmpfs `/dev/shm/...`, falling
 * back to `/tmp/...`, both outside the /work mount; host: a per-process 0700
 * temp dir):
 *
 *   D/token                          mode 600 — the current token (rewritten on refresh)
 *   D/git-credential-claude-threads  git credential helper (reads D/token)
 *   D/bin/gh                         wrapper that sets GH_TOKEN from D/token for one invocation
 *
 * Everything here is pure string construction so it can be tested by actually
 * executing the generated scripts under `sh`/`bash` with a temp directory.
 */

/** POSIX-shell single-quote escaping. */
export function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

export const GIT_HELPER_NAME = 'git-credential-claude-threads';

const UNAVAILABLE_HINT =
  'claude-threads: no GitHub token available. Connect GitHub in Geode (Settings → GitHub), or set GH_TOKEN yourself.';

/**
 * git credential helper. Answers only `get`, only for https github.com, and
 * only when the token file exists and is non-empty; otherwise it stays silent
 * (so git falls through to other helpers) and prints a hint to stderr.
 */
export function buildGitHelperScript(dir: string): string {
  return `#!/bin/sh
# Generated by Claude Threads. Serves the Geode GitHub connection token to git.
[ "$1" = "get" ] || exit 0
protocol=; host=
while IFS= read -r line; do
  [ -z "$line" ] && break
  case "$line" in
    protocol=*) protocol=\${line#protocol=} ;;
    host=*) host=\${line#host=} ;;
  esac
done
[ "$protocol" = "https" ] && [ "$host" = "github.com" ] || exit 0
f=${shellQuote(`${dir}/token`)}
if [ -s "$f" ]; then
  printf 'username=x-access-token\\npassword=%s\\n' "$(cat "$f")"
else
  echo ${shellQuote(UNAVAILABLE_HINT)} >&2
fi
exit 0
`;
}

/**
 * `gh` wrapper placed first on PATH. It exports GH_TOKEN for the single `gh`
 * process it execs, so the token is never in the long-lived shell environment.
 *
 * `respectExistingAuth` (host): if GH_TOKEN/GITHUB_TOKEN is already set, or the
 * user is logged in with `gh auth login`, their credentials win untouched. In
 * the container there is no prior login, so the connection is always used.
 */
export function buildGhWrapperScript(dir: string, respectExistingAuth: boolean): string {
  const bin = `${dir}/bin`;
  return `#!/bin/sh
# Generated by Claude Threads. Runs the real gh with the Geode GitHub connection token.
ct_bin=${shellQuote(bin)}
ct_path=
old_ifs=$IFS; IFS=:
for p in $PATH; do
  [ "$p" = "$ct_bin" ] && continue
  ct_path=\${ct_path:+$ct_path:}$p
done
IFS=$old_ifs
PATH=$ct_path
export PATH
f=${shellQuote(`${dir}/token`)}
if [ -z "\${GH_TOKEN:-}" ] && [ -z "\${GITHUB_TOKEN:-}" ] && [ -s "$f" ]; then
${respectExistingAuth
    ? `  if ! gh auth token >/dev/null 2>&1; then GH_TOKEN=$(cat "$f"); export GH_TOKEN; fi`
    : `  GH_TOKEN=$(cat "$f"); export GH_TOKEN`}
fi
exec gh "$@"
`;
}

export interface IdentityArgs { name: string; email: string }

/**
 * One shell command (run via `bash -lc` inside the container) that installs the
 * helper, the gh wrapper, git config and PATH, all under the first usable
 * candidate dir. Contains no token. Idempotent.
 *
 * Git config is written with `--global` **inside the container** (its own
 * ~/.gitconfig, never the host's or the worktree's). The identity is set only
 * if the container has none, and repo-local config in /work still overrides it.
 */
export function buildContainerInstallCommand(opts: {
  dirCandidates: string[];
  identity?: IdentityArgs | null;
}): string {
  const first = opts.dirCandidates.map((d) => shellQuote(d)).join(' ');
  // Scripts are written by a here-doc per candidate resolved at runtime, so the
  // literal directory has to appear inside them: render them with a placeholder
  // and substitute the resolved $D.
  const helper = buildGitHelperScript('__CT_DIR__');
  const ghw = buildGhWrapperScript('__CT_DIR__', false);
  // BSD and GNU sed disagree on -i, so substitute through a pipe instead.
  const lines = [
    'set -e',
    'umask 077',
    'D=',
    `for c in ${first}; do if mkdir -p "$c/bin" 2>/dev/null; then D=$c; break; fi; done`,
    '[ -n "$D" ] || { echo "claude-threads: no writable runtime dir for GitHub credentials" >&2; exit 1; }',
    'chmod 700 "$D" "$D/bin"',
    `sed "s#__CT_DIR__#$D#g" > "$D/${GIT_HELPER_NAME}" <<'CT_HELPER_EOF'`,
    helper.replace(/\n$/, ''),
    'CT_HELPER_EOF',
    'sed "s#__CT_DIR__#$D#g" > "$D/bin/gh" <<\'CT_GH_EOF\'',
    ghw.replace(/\n$/, ''),
    'CT_GH_EOF',
    `chmod 700 "$D/${GIT_HELPER_NAME}" "$D/bin/gh"`,
    // Additive, container-local git config; drop any earlier claude-threads helper first.
    `git config --global --unset-all credential.https://github.com.helper 'claude-threads' 2>/dev/null || true`,
    `git config --global --add credential.https://github.com.helper "$D/${GIT_HELPER_NAME}"`,
    // Login shells (bash -lc) put the wrapper ahead of the real gh.
    'p=$HOME/.profile; [ -f "$HOME/.bash_profile" ] && p=$HOME/.bash_profile; [ -f "$HOME/.bash_login" ] && [ ! -f "$HOME/.bash_profile" ] && p=$HOME/.bash_login',
    'if [ -f "$p" ]; then sed "/# >>> claude-threads github >>>/,/# <<< claude-threads github <<</d" "$p" > "$p.ct-tmp" && mv "$p.ct-tmp" "$p"; fi',
    'printf \'%s\\n\' "# >>> claude-threads github >>>" "export PATH=\\"$D/bin:\\$PATH\\"" "# <<< claude-threads github <<<" >> "$p"',
  ];
  if (opts.identity) {
    lines.push(
      `git config --global --get user.name >/dev/null 2>&1 || git config --global user.name ${shellQuote(opts.identity.name)}`,
      `git config --global --get user.email >/dev/null 2>&1 || git config --global user.email ${shellQuote(opts.identity.email)}`,
    );
  }
  lines.push('printf %s "$D"');
  return lines.join('\n');
}

/** Command that atomically replaces D/token from stdin. Reads the token from stdin only — never argv. */
export function buildContainerWriteTokenCommand(dirCandidates: string[]): string {
  const cands = dirCandidates.map((d) => shellQuote(d)).join(' ');
  return [
    'umask 077',
    'D=',
    `for c in ${cands}; do if [ -d "$c" ]; then D=$c; break; fi; done`,
    '[ -n "$D" ] || { echo "claude-threads: credential dir missing" >&2; exit 1; }',
    'cat > "$D/token.tmp" && mv -f "$D/token.tmp" "$D/token"',
  ].join('\n');
}

export function buildContainerClearTokenCommand(dirCandidates: string[]): string {
  const cands = dirCandidates.map((d) => shellQuote(d)).join(' ');
  return `for c in ${cands}; do rm -f "$c/token" "$c/token.tmp"; done`;
}

/** Runtime-dir candidates inside the container: tmpfs first, never under /work. */
export const CONTAINER_DIR_CANDIDATES = ['/dev/shm/claude-threads-github', '/tmp/claude-threads-github'] as const;

// ── Host environment ──────────────────────────────────────────────────────────

/**
 * Environment additions that make host `git` use the helper (additively) and
 * put the gh wrapper first on PATH. GIT_CONFIG_COUNT entries are appended after
 * any the caller already has, and `credential.helper` is multi-valued, so
 * existing helpers (osxkeychain, gh, …) are consulted first and keep working.
 */
export function buildHostGitEnv(opts: {
  dir: string;
  baseEnv: Record<string, string | undefined>;
  identity?: Partial<IdentityArgs> | null;
}): Record<string, string> {
  const existing = Number.parseInt(opts.baseEnv.GIT_CONFIG_COUNT ?? '0', 10);
  let n = Number.isFinite(existing) && existing > 0 ? existing : 0;
  const out: Record<string, string> = {};
  const add = (key: string, value: string) => {
    out[`GIT_CONFIG_KEY_${n}`] = key;
    out[`GIT_CONFIG_VALUE_${n}`] = value;
    n += 1;
  };
  add('credential.https://github.com.helper', `${opts.dir}/${GIT_HELPER_NAME}`);
  if (opts.identity?.name) add('user.name', opts.identity.name);
  if (opts.identity?.email) add('user.email', opts.identity.email);
  out.GIT_CONFIG_COUNT = String(n);
  // No trailing ':' when PATH is unset — an empty entry would put the cwd on PATH.
  out.PATH = opts.baseEnv.PATH ? `${opts.dir}/bin:${opts.baseEnv.PATH}` : `${opts.dir}/bin`;
  return out;
}

/** Removes the env additions {@link buildHostGitEnv} makes, for sessions that run inside the sandbox VM. */
export function stripHostOnlyGitEnv(env: Record<string, string>): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(env)) {
    if (k === 'PATH' || k === 'GIT_CONFIG_COUNT' || /^GIT_CONFIG_(KEY|VALUE)_\d+$/.test(k)) continue;
    out[k] = v;
  }
  return out;
}
