/** Stable type-only contract for Agent Threads peer plugins. */
export type AgentHarness = 'claude' | 'codex';
export type ThreadStatus = 'waiting' | 'active' | 'error' | 'archived' | 'reconnecting';
export type PublicErrorCode = 'PLUGIN_UNAVAILABLE' | 'THREAD_NOT_FOUND' | 'RUN_NOT_FOUND' | 'RUN_FAILED' | 'RUN_INTERRUPTED' | 'THREAD_BUSY' | 'IDEMPOTENCY_CONFLICT' | 'TRACE_NOT_FOUND' | 'CURSOR_INVALID' | 'CONSTRAINT_UNSUPPORTED' | 'ORCHESTRATOR_NOT_FOUND' | 'INVALID_ARGUMENT';
export interface PublicError { readonly code: PublicErrorCode; readonly message: string }
export interface Disposable { dispose(): void }
export interface CorrelationInput { readonly ownerPluginId?: string; readonly idempotencyKey?: string }
export interface CreateThreadInput extends CorrelationInput { readonly title?: string; readonly cwd?: string; readonly projectId?: string; readonly agentHarness?: AgentHarness; readonly origin?: string; readonly externalJobId?: string; readonly ephemeral?: boolean; readonly background?: boolean }
export type ProvisionalCommitResult = { readonly status: 'committed' | 'already-committed' | 'rolled-back'; readonly threadId: string };
export type ProvisionalRollbackResult = { readonly status: 'rolled-back' | 'already-rolled-back' | 'committed'; readonly threadId: string };
export interface ProvisionalThreadHandle { readonly threadId: string; commit(): Promise<ProvisionalCommitResult>; rollback(): Promise<ProvisionalRollbackResult> }
export interface SendInput extends CorrelationInput { readonly prompt: string }
export interface MessageSnapshot { readonly id: string; readonly role: 'user' | 'assistant' | 'compact' | 'notice'; readonly content: string; readonly timestamp: number }
export interface ThreadSummary { readonly id: string; readonly title: string; readonly status: ThreadStatus; readonly reviewed: boolean; readonly cwd?: string; readonly projectId?: string; readonly agentHarness: AgentHarness; readonly origin?: string; readonly externalJobId?: string; readonly ephemeral?: boolean; readonly background?: boolean; readonly createdAt: number; readonly updatedAt: number; readonly isRunning: boolean; readonly messageCount: number }
export interface ThreadSnapshot extends ThreadSummary { readonly messages: readonly MessageSnapshot[] }
export interface PublicUsage { readonly inputTokens: number; readonly outputTokens: number; readonly costUsd: number; readonly durationMs?: number; readonly turns?: number }
export type RunResult = { readonly status: 'completed'; readonly runId: string; readonly threadId: string; readonly finalMessage?: MessageSnapshot; readonly usage?: PublicUsage } | { readonly status: 'failed'; readonly runId: string; readonly threadId: string; readonly error: PublicError } | { readonly status: 'timed_out'; readonly runId: string; readonly threadId: string };
export type PublicThreadEvent = { readonly kind: 'run.started'; readonly threadId: string; readonly runId: string; readonly at: number } | { readonly kind: 'message.completed'; readonly threadId: string; readonly runId?: string; readonly message: MessageSnapshot; readonly at: number } | { readonly kind: 'run.completed'; readonly threadId: string; readonly runId: string; readonly finalMessage?: MessageSnapshot; readonly at: number } | { readonly kind: 'run.failed'; readonly threadId: string; readonly runId: string; readonly error: PublicError; readonly at: number } | { readonly kind: 'thread.removed'; readonly threadId: string; readonly at: number };
export interface TraceSource { readonly sourceId: string; readonly threadId: string; readonly projectId?: string; readonly harness: AgentHarness; readonly revision: string; readonly contentHash: string; readonly byteLength: number; readonly updatedAt: number }
export interface TraceSourcePage { readonly sources: readonly TraceSource[]; readonly nextCursor?: string; readonly eof: boolean }
export interface SkillRunOutcome { readonly invokedSkill: string; readonly runOutcome: 'success' | 'failure'; readonly invocationIndex: number }
export interface TraceEvent { readonly index: number; readonly timestamp: string; readonly type: string; readonly invokedSkill?: string; readonly skillLoadOutcome?: 'loaded'; readonly skillRunOutcomes?: readonly SkillRunOutcome[]; readonly data: unknown }
export interface TraceChunk { readonly sourceId: string; readonly revision: string; readonly contentHash: string; readonly cursor?: string; readonly nextCursor: string; readonly eof: boolean; readonly events: readonly TraceEvent[] }
export type PublicTraceEvent = { readonly kind: 'trace.updated' | 'trace.removed'; readonly sourceId: string; readonly revision: string; readonly at: number };
export interface ConstrainedRunInput { readonly ownerPluginId: string; readonly idempotencyKey: string; readonly harness: 'claude'; readonly model: string; readonly systemInstructions: string; readonly prompt: string; readonly maxTurns: 1; readonly maxBudgetUsd: number; readonly timeoutMs: number }
export type ConstrainedRunResult = { readonly status: 'running'; readonly runId: string } | { readonly status: 'completed'; readonly runId: string; readonly output: string; readonly model: string; readonly usage: PublicUsage } | { readonly status: 'failed' | 'cancelled'; readonly runId: string; readonly error: PublicError };
export interface OrchestratorSnapshot { readonly id: string; readonly kind: 'portfolio' | 'project'; readonly threadId: string; readonly title: string; readonly projectId?: string }
export interface AgentToolDefinition { readonly type: 'function'; readonly name: string; readonly description: string; readonly parameters: Readonly<Record<string, unknown>> }
export interface AgentToolBundle { readonly tools: readonly AgentToolDefinition[]; execute(name: string, args: Record<string, unknown>): Promise<string> }
export interface McpRegisterInput { readonly name: string; readonly type: 'stdio' | 'http' | 'sse' | 'oauth'; readonly command?: string; readonly args?: readonly string[]; readonly env?: Readonly<Record<string, string>>; readonly url?: string; readonly headers?: Readonly<Record<string, string>>; readonly scopes?: string; readonly tools?: { readonly allow?: readonly string[]; readonly deny?: readonly string[] }; readonly clientId?: string; readonly authorizationServerUrl?: string; readonly redirectUri?: string }
export interface McpRegistrationResult { success: boolean; status: 'registered' | 'unchanged' | 'conflict' | 'invalid' | 'cancelled' | 'unavailable' | 'failed'; message: string; requiredVariables?: string[] }
export interface RequestSecretInput { readonly secretName: string; readonly reason: string; readonly force?: boolean }
export type RequestSecretResult = { readonly success: true; readonly secretName: string; readonly alreadyExisted: boolean } | { readonly success: false; readonly reason: string };
export interface PeerIdentity { readonly pluginId: string; readonly displayName?: string }
export type MessageContentJson = null | boolean | number | string | readonly MessageContentJson[] | { readonly [key: string]: MessageContentJson };
export interface MessageContentRef { readonly providerId: string; readonly id: string; readonly schemaVersion: number; readonly title: string; readonly data: Readonly<Record<string, MessageContentJson>> }
export interface MessageContentContext { readonly threadId: string; readonly messageId: string; readonly signal: AbortSignal }
export type MessageContentPresentation = { readonly kind: 'card'; readonly title: string; readonly subtitle?: string; readonly icon?: string; readonly body?: string; readonly actions?: readonly ArtifactAction[] } | { readonly kind: 'image'; readonly title: string; readonly subtitle?: string; readonly icon?: string; readonly src: string; readonly alt: string; readonly actions?: readonly ArtifactAction[] } | { readonly kind: 'document'; readonly title: string; readonly subtitle?: string; readonly icon?: string; readonly html: string; readonly height?: number; readonly actions?: readonly ArtifactAction[] };
export interface MessageContentActionHost { readonly signal: AbortSignal; openView(state: { type: string; state?: Record<string, unknown> }): Promise<ArtifactViewPlacement> }
export interface MessageContentContribution { readonly providerId: string; present(ref: MessageContentRef, context: MessageContentContext): MessageContentPresentation | Promise<MessageContentPresentation>; invoke?(actionId: string, ref: MessageContentRef, context: MessageContentContext, host: MessageContentActionHost): Promise<ArtifactActionResult> }
export type MessageContentRegistrationResult = { readonly success: true; readonly status: 'registered'; readonly providerId: string; readonly dispose: () => void } | { readonly success: false; readonly status: 'invalid' | 'conflict' | 'unavailable'; readonly providerId: string; readonly message: string; readonly dispose: () => void };
export interface ThreadArtifactRef { readonly providerId: string; readonly kind: string; readonly schemaVersion: number; readonly id: string; readonly title: string; readonly data: unknown; readonly storageRoot?: string }
export interface ArtifactAction { readonly id: string; readonly label: string; readonly tooltip?: string; readonly variant?: 'primary' | 'secondary'; readonly icon?: string; readonly shortLabel?: string }
export interface ArtifactPresentation { readonly title: string; readonly subtitle?: string; readonly icon?: string; readonly actions: readonly ArtifactAction[] }
export type ArtifactActionResult = { readonly status: 'ok'; readonly message?: string } | { readonly status: 'warning'; readonly message: string } | { readonly status: 'error'; readonly message: string };
export type ArtifactViewPlacement = 'context-panel' | 'tab' | 'unavailable';
export interface ArtifactActionHost { openView(state: { type: string; state?: Record<string, unknown> }): Promise<ArtifactViewPlacement>; revealInFolder(absolutePath: string): Promise<boolean>; updateArtifact(patch: { title?: string; data?: unknown }): Promise<void> }
export interface ArtifactContribution { readonly providerId: string; readonly kinds: readonly string[]; present(ref: ThreadArtifactRef): ArtifactPresentation; invoke(actionId: string, ref: ThreadArtifactRef, host: ArtifactActionHost): Promise<ArtifactActionResult> }
export type ArtifactRegistrationResult = { readonly success: true; readonly status: 'registered'; readonly providerId: string; readonly dispose: () => void } | { readonly success: false; readonly status: 'invalid' | 'conflict'; readonly providerId: string; readonly message: string; readonly dispose: () => void };
export type ArtifactAttachResult = { readonly success: true; readonly status: 'attached' | 'updated'; readonly artifactId: string } | { readonly success: false; readonly status: 'invalid' | 'conflict' | 'unknown-provider' | 'thread-not-found' | 'unavailable'; readonly artifactId: string; readonly message: string };
export type ArtifactMutationResult = { readonly success: true; readonly status: 'updated' | 'detached'; readonly artifactId: string } | { readonly success: false; readonly status: 'invalid' | 'conflict' | 'unknown-provider' | 'thread-not-found' | 'artifact-not-found' | 'unavailable'; readonly artifactId: string; readonly message: string };
export interface ArtifactPatch { readonly title?: string; readonly data?: unknown; readonly storageRoot?: string }
export interface ThreadPermissionSnapshot { readonly threadId: string; readonly effectivePermissionMode: 'default' | 'acceptEdits' | 'bypassPermissions' | 'plan' | 'dontAsk' | 'auto'; readonly overridden: boolean; readonly planApprovalPending: boolean; readonly questionPending: boolean }
export type StorageAllocationResult = { readonly success: true; readonly status: 'allocated' | 'existing'; readonly artifactId: string; readonly path: string } | { readonly success: false; readonly status: 'invalid' | 'conflict' | 'unknown-provider' | 'thread-not-found' | 'unavailable'; readonly artifactId: string; readonly message: string };
export interface AgentToolResult { readonly content: readonly { readonly type: 'text'; readonly text: string }[]; readonly isError?: boolean }
export interface AgentToolHost { permissions(): Promise<ThreadPermissionSnapshot | null>; allocateStorage(artifactId: string): Promise<StorageAllocationResult> }
export interface AgentToolContribution { readonly name: string; readonly description: string; readonly inputSchema: unknown; readonly alwaysLoad?: boolean; readonly requiresApproval?: boolean; invoke(threadId: string, args: Record<string, unknown>, host: AgentToolHost): Promise<AgentToolResult> }
export type SlashCommandScope = 'thread' | 'dispatch';
export interface SlashCommandContext { readonly surface: SlashCommandScope; readonly text: string; readonly args: string; readonly threadId?: string; readonly agentHarness?: 'claude' | 'codex'; readonly projectId?: string; readonly hasImages: boolean; readonly hasAttachment: boolean }
export interface SlashCommandHost { readonly signal: AbortSignal; report(message: string, isError?: boolean): void }
export interface SlashCommandResult { readonly status: 'ok' | 'error'; readonly message?: string }
export interface SlashCommandHandler { readonly description: string; invoke(context: Readonly<SlashCommandContext>, host: SlashCommandHost): Promise<SlashCommandResult> }
export interface SlashCommandContribution { readonly name: string; readonly thread?: SlashCommandHandler; readonly dispatch?: SlashCommandHandler }
export type SlashCommandRegistrationResult = { readonly success: true; readonly status: 'registered'; readonly name: string; readonly dispose: () => void } | { readonly success: false; readonly status: 'invalid' | 'conflict' | 'unavailable'; readonly name: string; readonly message: string; readonly dispose: () => void };
export type AgentToolRegistrationResult = { readonly success: true; readonly status: 'registered'; readonly name: string; readonly dispose: () => void } | { readonly success: false; readonly status: 'invalid' | 'conflict' | 'unavailable'; readonly name: string; readonly message: string; readonly dispose: () => void };
export interface AgentThreadsApiV1 {
  readonly apiVersion: 1; readonly generation: string; readonly capabilities: readonly string[];
  readonly threads: { list(query?: { readonly projectId?: string | null; readonly status?: ThreadStatus; readonly limit?: number }): Promise<readonly ThreadSummary[]>; get(threadId: string): Promise<ThreadSnapshot | null>; create(input: CreateThreadInput): Promise<{ readonly threadId: string }>; beginProvisional(owner: PeerIdentity, input: CreateThreadInput): Promise<ProvisionalThreadHandle>; send(threadId: string, input: SendInput): Promise<{ readonly runId: string }>; wait(runId: string, options?: { readonly timeoutMs?: number }): Promise<RunResult>; cancel(runId: string): Promise<Exclude<RunResult, { status: 'timed_out' }>>; open(threadId: string): Promise<void>; subscribe(listener: (event: PublicThreadEvent) => void): Disposable; permissions(threadId: string): Promise<ThreadPermissionSnapshot | null> };
  readonly traces: { listSources(options?: { readonly cursor?: string; readonly limit?: number }): Promise<TraceSourcePage>; readChunk(sourceId: string, options?: { readonly cursor?: string; readonly limit?: number }): Promise<TraceChunk>; subscribe(listener: (event: PublicTraceEvent) => void): Disposable };
  readonly constrainedRuns: { create(input: ConstrainedRunInput): Promise<{ readonly runId: string }>; get(runId: string): Promise<ConstrainedRunResult>; wait(runId: string, options?: { readonly timeoutMs?: number }): Promise<ConstrainedRunResult>; cancel(runId: string): Promise<ConstrainedRunResult> };
  readonly orchestrators: { list(): Promise<readonly OrchestratorSnapshot[]>; dispatch(target: { readonly id: string }, input: SendInput): Promise<{ readonly runId: string }> };
  readonly agentTools: { createBundle(profile: 'voice-orchestration'): AgentToolBundle };
  readonly mcp: { register(input: McpRegisterInput): Promise<McpRegistrationResult>; requestSecret(input: RequestSecretInput): Promise<RequestSecretResult> };
  readonly extensions: { registerArtifactProvider(owner: PeerIdentity, contribution: ArtifactContribution): ArtifactRegistrationResult; registerAgentTool(owner: PeerIdentity, contribution: AgentToolContribution): AgentToolRegistrationResult; registerSlashCommand(owner: PeerIdentity, contribution: SlashCommandContribution): SlashCommandRegistrationResult; registerMessageContentProvider(owner: PeerIdentity, contribution: MessageContentContribution): MessageContentRegistrationResult };
  readonly messageContent: { formatReference(ref: MessageContentRef): string };
  readonly artifacts: { list(threadId: string): Promise<readonly ThreadArtifactRef[]>; attach(owner: PeerIdentity, threadId: string, ref: ThreadArtifactRef): Promise<ArtifactAttachResult>; update(owner: PeerIdentity, threadId: string, artifactId: string, patch: ArtifactPatch): Promise<ArtifactMutationResult>; detach(owner: PeerIdentity, threadId: string, artifactId: string): Promise<ArtifactMutationResult>; invokeAction(threadId: string, artifactId: string, actionId: string): Promise<ArtifactActionResult>; allocateStorage(threadId: string, artifactId: string): Promise<StorageAllocationResult> };
}
export type ClaudeThreadsApiV1 = AgentThreadsApiV1;
